openapi: 3.0.0
info:
  title: Billing Service
  description: 	Handles invoicing, refunds, and recurring payment logic
  x-cortex-tag: billing-service
  x-cortex-type: service
  x-cortex-groups:
    - financial-systems
  x-cortex-owners:
    - type: group
      name: cortex-workshops/payments-team
      provider: GITHUB
  x-cortex-git:
    github:
      alias: cortex
      repository: cortex-workshops/billing-service
