openapi: 3.0.0
info:
  title: Billing Service
  description: Handles invoicing, refunds, and recurring payment logic
  x-cortex-tag: billing-service
  x-cortex-type: service
  x-cortex-groups:
    - financial-systems
  x-cortex-owners:
    - type: group
      name: cortex-workshops/payments-team
      provider: GITHUB
  x-cortex-git:
    github:
      alias: cortex
      repository: cortex-workshops/billing-service
  x-cortex-issues:
    jira:
      labels:
        - name: payments
  x-cortex-link:
  - name: Logs
    type: logs
    url: https://datadog.com
  - name: Billing API Spec
    type: OPENAPI
    url: ./swagger.json
  x-cortex-oncall:
    pagerduty:
      id: P8U8OR1   # PagerDuty Service ID
      type: SERVICE
  x-cortex-dependency:
  - tag: test-database
